version: '3.8'
name: chatapp
services:
  mongo:
    image: mongo:6.0.4-jammy
    restart: always
    volumes:
      - ../mongo-data:/data/db
    env_file:
      - ./.env.mongo

  mongo-express:
    image: mongo-express:latest
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    env_file:
      - ./.env.mongo-express

  chatapp-ui:
    depends_on:
      - chatapp-api
    image: ghcr.io/lucaschan1020/chatapp-ui:1.4.1
    # build:
    #   context: ../chatapp-ui
    #   dockerfile: Dockerfile
    #   args:
    #     REACT_APP_GAPI_CLIENTID: ${GAPI_CLIENTID}
    
  chatapp-api:
    depends_on:
      - mongo
    restart: on-failure
    image: ghcr.io/lucaschan1020/chatapp-api:1.4.1
    # build:
    #   context: ../chatapp-api
    #   dockerfile: Dockerfile
    env_file:
      - ../chatapp-api/.env.production

  chatapp-gateway:
    depends_on:
      - chatapp-api
      - chatapp-ui
    restart: always
    image: ghcr.io/lucaschan1020/chatapp-gateway:1.4.1
    volumes:
      - ./certs:/etc/nginx/certs
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443