version: '3.8'
name: chatapp
services:
  mongo:
    image: mongo:6.0.4-jammy
    restart: always
    volumes:
      - ../mongo-data:/data/db
    env_file:
      - ./.env.mongo

  mongo-express:
    image: mongo-express:latest
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    env_file:
      - ./.env.mongo-express

  chatapp-ui:
    depends_on:
      - chatapp-api
    build:
      context: ../chatapp-ui
      dockerfile: Dockerfile
      args:
        REACT_APP_GAPI_CLIENTID: ${GAPI_CLIENTID}
    
  chatapp-api:
    depends_on:
      - mongo
    build:
      context: ../chatapp-api
      dockerfile: Dockerfile
    env_file:
      - ../chatapp-api/.env.production

  chatapp-gateway:
    depends_on:
      - chatapp-api
      - chatapp-ui
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'