name: continuous-integration

on:
  pull_request:
    branches: ['master']

env:
  IMAGE_TAG: ghcr.io/${{ github.repository }}:ci-test

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.dev
          push: false
          tags: ${{ env.IMAGE_TAG }}
